name: ci
on: [ workflow_dispatch ]
jobs:
  hello:
    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-tools-deps
    steps:
      - uses: actions/checkout@v2
      - name: Say hello
        run: clj -Adeploy
