environment: deploy
name: ci
on: [ workflow_dispatch ]
jobs:
  deploy-clojars:
    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-tools-deps
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: clj -Adeploy
